//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8009.
// 
namespace CE_Network.local.strandmollen.barcode {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="bcSoap", Namespace="http://barcode.strandmollen.local/")]
    public partial class bc : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public bc() {
            this.Url = "http://barcode.strandmollen.local/bc.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://barcode.strandmollen.local/StoreData", RequestNamespace="http://barcode.strandmollen.local/", ResponseNamespace="http://barcode.strandmollen.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet StoreData(System.Data.DataSet ds, int copies, string Printer, System.DateTime LastCall) {
            object[] results = this.Invoke("StoreData", new object[] {
                        ds,
                        copies,
                        Printer,
                        LastCall});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginStoreData(System.Data.DataSet ds, int copies, string Printer, System.DateTime LastCall, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("StoreData", new object[] {
                        ds,
                        copies,
                        Printer,
                        LastCall}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndStoreData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://barcode.strandmollen.local/RePrint", RequestNamespace="http://barcode.strandmollen.local/", ResponseNamespace="http://barcode.strandmollen.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RePrint(System.Data.DataSet ds, int copies, string Printer) {
            object[] results = this.Invoke("RePrint", new object[] {
                        ds,
                        copies,
                        Printer});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRePrint(System.Data.DataSet ds, int copies, string Printer, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RePrint", new object[] {
                        ds,
                        copies,
                        Printer}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndRePrint(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://barcode.strandmollen.local/GetData", RequestNamespace="http://barcode.strandmollen.local/", ResponseNamespace="http://barcode.strandmollen.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetData() {
            object[] results = this.Invoke("GetData", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetData(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetData", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://barcode.strandmollen.local/Printers", RequestNamespace="http://barcode.strandmollen.local/", ResponseNamespace="http://barcode.strandmollen.local/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Printers() {
            object[] results = this.Invoke("Printers", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPrinters(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Printers", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndPrinters(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
    }
}
