//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6400
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSStringTest.StringWriterWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArticleFile", Namespace="http://srv-web-03/webservices")]
    [System.SerializableAttribute()]
    public partial class ArticleFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSStringTest.StringWriterWS.ArrayOfString AllLinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WSStringTest.StringWriterWS.ArrayOfString AllLines {
            get {
                return this.AllLinesField;
            }
            set {
                if ((object.ReferenceEquals(this.AllLinesField, value) != true)) {
                    this.AllLinesField = value;
                    this.RaisePropertyChanged("AllLines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://srv-web-03/webservices", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://srv-web-03/webservices", ConfigurationName="StringWriterWS.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name WriteMe from namespace http://srv-web-03/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://srv-web-03/webservices/StringWriter", ReplyAction="*")]
        WSStringTest.StringWriterWS.StringWriterResponse StringWriter(WSStringTest.StringWriterWS.StringWriterRequest request);
        
        // CODEGEN: Generating message contract since element name Filename from namespace http://srv-web-03/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://srv-web-03/webservices/StringReader", ReplyAction="*")]
        WSStringTest.StringWriterWS.StringReaderResponse StringReader(WSStringTest.StringWriterWS.StringReaderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StringWriterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StringWriter", Namespace="http://srv-web-03/webservices", Order=0)]
        public WSStringTest.StringWriterWS.StringWriterRequestBody Body;
        
        public StringWriterRequest() {
        }
        
        public StringWriterRequest(WSStringTest.StringWriterWS.StringWriterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://srv-web-03/webservices")]
    public partial class StringWriterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WriteMe;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Location;
        
        public StringWriterRequestBody() {
        }
        
        public StringWriterRequestBody(string WriteMe, string Filename, string Location) {
            this.WriteMe = WriteMe;
            this.Filename = Filename;
            this.Location = Location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StringWriterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StringWriterResponse", Namespace="http://srv-web-03/webservices", Order=0)]
        public WSStringTest.StringWriterWS.StringWriterResponseBody Body;
        
        public StringWriterResponse() {
        }
        
        public StringWriterResponse(WSStringTest.StringWriterWS.StringWriterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://srv-web-03/webservices")]
    public partial class StringWriterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool StringWriterResult;
        
        public StringWriterResponseBody() {
        }
        
        public StringWriterResponseBody(bool StringWriterResult) {
            this.StringWriterResult = StringWriterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StringReaderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StringReader", Namespace="http://srv-web-03/webservices", Order=0)]
        public WSStringTest.StringWriterWS.StringReaderRequestBody Body;
        
        public StringReaderRequest() {
        }
        
        public StringReaderRequest(WSStringTest.StringWriterWS.StringReaderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://srv-web-03/webservices")]
    public partial class StringReaderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Filename;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Location;
        
        public StringReaderRequestBody() {
        }
        
        public StringReaderRequestBody(string Filename, string Location) {
            this.Filename = Filename;
            this.Location = Location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StringReaderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StringReaderResponse", Namespace="http://srv-web-03/webservices", Order=0)]
        public WSStringTest.StringWriterWS.StringReaderResponseBody Body;
        
        public StringReaderResponse() {
        }
        
        public StringReaderResponse(WSStringTest.StringWriterWS.StringReaderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://srv-web-03/webservices")]
    public partial class StringReaderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSStringTest.StringWriterWS.ArticleFile StringReaderResult;
        
        public StringReaderResponseBody() {
        }
        
        public StringReaderResponseBody(WSStringTest.StringWriterWS.ArticleFile StringReaderResult) {
            this.StringReaderResult = StringReaderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface Service1SoapChannel : WSStringTest.StringWriterWS.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<WSStringTest.StringWriterWS.Service1Soap>, WSStringTest.StringWriterWS.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSStringTest.StringWriterWS.StringWriterResponse WSStringTest.StringWriterWS.Service1Soap.StringWriter(WSStringTest.StringWriterWS.StringWriterRequest request) {
            return base.Channel.StringWriter(request);
        }
        
        public bool StringWriter(string WriteMe, string Filename, string Location) {
            WSStringTest.StringWriterWS.StringWriterRequest inValue = new WSStringTest.StringWriterWS.StringWriterRequest();
            inValue.Body = new WSStringTest.StringWriterWS.StringWriterRequestBody();
            inValue.Body.WriteMe = WriteMe;
            inValue.Body.Filename = Filename;
            inValue.Body.Location = Location;
            WSStringTest.StringWriterWS.StringWriterResponse retVal = ((WSStringTest.StringWriterWS.Service1Soap)(this)).StringWriter(inValue);
            return retVal.Body.StringWriterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSStringTest.StringWriterWS.StringReaderResponse WSStringTest.StringWriterWS.Service1Soap.StringReader(WSStringTest.StringWriterWS.StringReaderRequest request) {
            return base.Channel.StringReader(request);
        }
        
        public WSStringTest.StringWriterWS.ArticleFile StringReader(string Filename, string Location) {
            WSStringTest.StringWriterWS.StringReaderRequest inValue = new WSStringTest.StringWriterWS.StringReaderRequest();
            inValue.Body = new WSStringTest.StringWriterWS.StringReaderRequestBody();
            inValue.Body.Filename = Filename;
            inValue.Body.Location = Location;
            WSStringTest.StringWriterWS.StringReaderResponse retVal = ((WSStringTest.StringWriterWS.Service1Soap)(this)).StringReader(inValue);
            return retVal.Body.StringReaderResult;
        }
    }
}
